name: theme_test
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-165.1.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # localization helper
  intl: ^0.17.0
  # localization automation
  intl_utils: ^2.4.0
  # a way to combine storybook and device frame featues
  device_preview: ^1.1.0
  screenshot_modes: ^1.0.0
  local_file_screenshot_processor: ^0.0.2

  flex_color_scheme: ^5.1.0
  presentation:
    path: "../presentation"



dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0
  # code metrics feedback
  dart_code_metrics: ^4.17.0
  # code generatio
  build_runner: ^2.2.0


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
# flutter intl for localization settings
flutter_intl:
  enabled: true   
  class_name: S   
  main_locale: en 
  arb_dir: lib/src/localization
  output_dir: lib/src/localization_gen
  use_deferred_loading: false

