name: designer_arch
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-165.1.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # localization helper
  intl: ^0.17.0
  # localization automation
  intl_utils: ^2.4.0
  # a way to combine storybook and device frame featues
  device_preview: ^1.1.0
  screenshot_modes: ^1.0.0
  local_file_screenshot_processor: ^0.0.2
  design_tools: ^0.3.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  # better bdd error feedback for unit tests
  shouldly: ^0.5.0+1
  mockito: ^5.2.0
  # mock generator
  mockor: ^1.2.1
  # better goldens
  golden_toolkit: ^0.13.0
  # page object testing patterns
  page_object: ^0.2.0
  # better widget bdd patterns
  given_when_then: ^0.2.0


  # more opinionated strict lint
  lint: ^1.8.2


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
# flutter intl for localization settings
flutter_intl:
  enabled: true   
  class_name: S   
  main_locale: en 
  arb_dir: lib/src/localization
  output_dir: lib/src/localization_gen
  use_deferred_loading: false

